### ISSUE TITLE
Cache entry must specify a value for Size when SizeLimit is set

### ISSUE THREAD

**Issue by byelmendes** [NetDevPack/Security.Jwt#13]
"NetDevPack.Security.Jwt.AspNetCore" Version="5.0.9"
"NetDevPack.Security.Jwt.Store.EntityFrameworkCore" Version="5.0.9"

Ao pedir o SigningCredentials atual a aplicação joga a exceção abaixo.
Esse erro somente acontece se já existe um token no banco de dados.

Cache entry must specify a value for Size when SizeLimit is set.

```
at Microsoft.Extensions.Caching.Memory.MemoryCache.SetEntry(CacheEntry entry)
   at Microsoft.Extensions.Caching.Memory.CacheEntry.Dispose()
   at Microsoft.Extensions.Caching.Memory.CacheExtensions.Set[TItem](IMemoryCache cache, Object key, TItem value, MemoryCacheEntryOptions options)
   at NetDevPack.Security.JwtSigningCredentials.Store.EntityFrameworkCore.DatabaseJsonWebKeyStore`1.GetCurrentKey(JsonWebKeyType jwkType)
   at NetDevPack.Security.JwtSigningCredentials.Store.EntityFrameworkCore.DatabaseJsonWebKeyStore`1.NeedsUpdate(JsonWebKeyType jsonWebKeyType)
   at NetDevPack.Security.JwtSigningCredentials.Jwks.JwksService.GetCurrentSigningCredentials(JwksOptions options)
   at xxx.Identity.Application.Token.JwtToken.GenerateToken(User user, UserTokenType userTokenType) in C:\Projects\xxx\xxx.Identity.Application\Token\JwtToken.cs:line 132
```

Também ocorre o erro se coloco a requisição 1 abaixo da outra.

![image](https://user-images.githubusercontent.com/10376877/119277189-8ef88c80-bbf4-11eb-992a-64f5c0eaf050.png)

![image](https://user-images.githubusercontent.com/10376877/119277195-95870400-bbf4-11eb-98dc-37c8b1f653bd.png)

O erro descrito acima acontece no momento de salvar o cache em memória.

![image](https://user-images.githubusercontent.com/10376877/119277843-4773ff80-bbf8-11eb-93c2-6b469558318b.png)

Ajustando o Size conforme imagem abaixo o erro é resolvido.

![image](https://user-images.githubusercontent.com/10376877/119280187-8c069780-bc06-11eb-999e-ff4942ff1f88.png)

**Não** estou utilizando o **IdentityServer4**!

**Comment by byelmendes** [comment]
Bruno, alguma previsão da correção dessa issue? Thx!!!

**Comment by brunohbrito** [comment]
Você poderia compartilhar como está seu Startup? Pois efetuei diversos testes aqui e não consegui simular o problema.

**Comment by byelmendes** [comment]
Meu startup está separado em diversas classes/extensions, alguma parte em específico que você gostaria que eu compartilhasse?

**Comment by brunohbrito** [comment]
Em algum lugar do Startup.cs você tem o configuração do JwksManager.

A configuração pode ser desde um simples:
```csharp
public void ConfigureServices(IServiceCollection services)
{
    services.AddJwksManager().PersistKeysToDatabaseStore<MyKeysContext>();
}
```

Até algo mais personalizado como:
```
public void ConfigureServices(IServiceCollection services)
{
    services.AddJwksManager(o =>
    {
        o.Jws = JwsAlgorithm.ES256;
        o.Jwe = JweAlgorithm.RsaOAEP.WithEncryption(Encryption.Aes128CbcHmacSha256);
    })
    .PersistKeysToDatabaseStore<MyKeysContext>();
}
```

E é nesse ponto que gostaria de saber como está configurado para poder efetuar uma simulação

**Comment by byelmendes** [comment]
Então, a configuração está na maneira mais simples.

```csharp
services.AddJwksManager().PersistKeysToDatabaseStore<SecurityKeysDbContext>();
```

**Comment by brunohbrito** [comment]
Eu realmente não consigo simular. Estou desconfiado que algum outro componente pode estar interferindo.

Será que pode me ajudar criando um projeto modelo? Eu atualizei os samples na branch [bug/slidingsize](https://github.com/NetDevPack/Security.Jwt/tree/bug/slidingsize/samples/Server.AsymmetricKey), se puder fazer um fork e demonstrar como chegar no bug ficaria grato.

**Comment by byelmendes** [comment]
Bruno, fiz alguns testes aqui e percebi que a minha lib de idempotência estava adicionando o DbContext com o AddEntityFrameworkSqlServer. Já havia trocado nos serviços, porém nessa lib não. Com isso o MemoryCache estava sendo configurado com um SizeLimit. Obrigado pela ajuda.

**Comment by brunohbrito** [comment]
Obrigado pelo retorno. Vou ver se consigo colocar uma validação para estourar um erro quando o SizeLimit for um limitante!
