### ISSUE TITLE
Single app with AddJwtBearer support

### ISSUE THREAD

**Issue by domagojmedo** [NetDevPack/Security.Jwt#14]
In examples, client app is separate from identity app. Is there a way to use the library without `.UseJwksDiscovery()` and setting the URL in client app since they are the same app. 
There is sample for same app but it doesn't use `.AddJwtBearer()` in startup, it just manually decodes JWT

Thanks

**Comment by brunohbrito** [comment]
Hi @domagojmedo, 

It's in my roadmap to do a feature like that. But unfortunately, at this moment you cant. Because there a lot of dependencies which we cant use at Startup to generate a Asymetric key.

**Comment by brunohbrito** [comment]
Hi,

The new version is available and now it's possible to support and validate jwt at the same api! Check docs for more info
