### ISSUE TITLE
Store you JWK at database with EntityFrameworkCore

### ISSUE THREAD

**Issue by fsantos-repay** [NetDevPack/Security.Jwt#36]
Hello,

I'm using the new version of 7.0.2 and it's not storing in the database in the table [SecurityKeys], in this case in sql server, can you help me?

**Comment by brunobritodev** [comment]
Yes, could you provide more details about your impl? A use case to test the problem

**Comment by fsantos-repay** [comment]
I implemented it like this here on github and put
services.AddJwksManager().PersistKeysToDatabaseStore<ApplicationDbContext>();

![image](https://user-images.githubusercontent.com/110242933/211566238-566473cb-574b-4ec3-b485-c31ca8b0de15.png)

**Comment by brunobritodev** [comment]
Great, the key isn't generated after you load your app. It generates when you ask for a key. A way to do it is going to your api at `https://localhost:<port>/jwks` and check if it's empty.

**Comment by fsantos-repay** [comment]
is not empty
![image](https://user-images.githubusercontent.com/110242933/211587765-57d0671c-3fae-49c9-b44a-e3a2fecea1ee.png)

**Comment by brunobritodev** [comment]
It's really strange, could you check if you are using DataProtection? e.g: `builder.Services.AddDataProtection()`

**Comment by fsantos-repay** [comment]
![image](https://user-images.githubusercontent.com/110242933/211625309-33212845-ac3d-4a17-8cfe-165cb9b692ae.png)

**Comment by brunobritodev** [comment]
My suspecious is that you've checked your database before the keys was created. This is a design of our component who could leads some people to mistakes. The keys is created immediatly after you request a key for the first time.

If there is any problem at your configuration, your Keys has to be at %LOCALAPPDATA%\ASP.NET\DataProtection-Keys. But isn't the case, looking to your configuration, the keys should be at `ApplicationDbContext`

**Comment by fsantos-repay** [comment]
how can i do that, sorry?

**Comment by brunobritodev** [comment]
This file indicates there is a misconfiguration, because this file is your key. Please check these fresh new examples 

1. [Default AspNet Implementation](https://github.com/NetDevPack/Security.Jwt/tree/master/samples/1_AspNet.Default) (Recommended).
2. Storing Jwk in a different place from ASP.NET [https://github.com/NetDevPack/Security.Jwt/tree/master/samples/2_AspNet.Store.EntityFramework]

**Comment by fsantos-repay** [comment]
I tested it, creating another project and it worked perfectly, so I'm going to refactor my project, because I already wanted to migrate to dotnet 7.

and then I'll come back to give feedback

**Comment by brunobritodev** [comment]
Could you share the error message ?

**Comment by fsantos-repay** [comment]
looks like its not able to do the save in  the table:
[LogCore-20230112.txt](https://github.com/NetDevPack/Security.Jwt/files/10401890/LogCore-20230112.txt)

**Comment by brunobritodev** [comment]
In your `ApplicationDbContext` there is any configuration overriding string MaxLenght ?

The column `Parameter` supposed to be `nvarchar(max)`, but instead it clearly have a limitation.

![image](https://user-images.githubusercontent.com/7241156/212083808-3c243387-cd46-4745-8b56-b321924fa800.png)

**Comment by brunobritodev** [comment]
A way to solve it, create a class:

```csharp
public class KeyMaterialMap : IEntityTypeConfiguration<KeyMaterial>
{
    public void Configure(EntityTypeBuilder<KeyMaterial> builder)
    {
        builder.HasKey(c => c.Id);

        builder.Property(c => c.Parameters)
            .HasMaxLength(8000)
            .IsRequired();
    }
}
```

Then at your `ApplicationDbContext`:
```
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.ApplyConfiguration(new KeyMaterialMap());
    base.OnModelCreating(modelBuilder);
}
```

**Comment by fsantos-repay** [comment]
very good my friend. thank you very much and sorry if i took up too much of your time
