### ISSUE TITLE
.NET 8.0 incompatibility with HS256

### ISSUE THREAD

**Issue by sherlock1982** [NetDevPack/Security.Jwt#47]
I use `IJwtService` with the following code to generate access token:

            var credentials = await jwtService.GetCurrentSigningCredentials();
            var tokenDescriptor = _jwtSecurityTokenHandler.CreateJwtSecurityToken(_issuer, _issuer,
                new ClaimsIdentity(claims), expires: DateTime.UtcNow.AddMinutes(60), signingCredentials: credentials);

I get here:

System.NotSupportedException: 'IDX10621: 'Microsoft.IdentityModel.Tokens.SymmetricSignatureProvider' supports: 'Microsoft.IdentityModel.Tokens.SecurityKey' of types: 'Microsoft.IdentityModel.Tokens.AsymmetricSecurityKey' or 'Microsoft.IdentityModel.Tokens.SymmetricSecurityKey'. SecurityKey received was of type 'Microsoft.IdentityModel.Tokens.JsonWebKey'.'

 [Might be related to](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1252)

Workaround is not to use HS256

**Comment by brunobritodev** [comment]
I got the same problem. I fixed it cleaning old keys from ASP.NET Dataprotection folder: eg: `C:\Users\<user>\AppData\Local\ASP.NET\DataProtection-Keys`. I know it's a workaround, but I don't why the parameters from Key was blank after change to .NET 8, maybe IDataProtector.

**Comment by maryammadzadeh** [comment]
Hmm.. Yeah as soon as we upgraded todotnet 8 this error appeared, we use JsonWebKeys for our own providers, how can the work around be to not use 256? for all key types?

**Comment by anderjoy** [comment]
I encountered the same problem but I didn't update to .net 8.0. I use persistence with entity framework (MSSQL). The key parameters were left blank for no apparent reason. We resolved this by deleting the table and restarting the API (workaround).

**Comment by anderjoy** [comment]
> I encountered the same problem but I didn't update to .net 8.0. I use persistence with entity framework (MSSQL). The key parameters were left blank for no apparent reason. We resolved this by deleting the table and restarting the API (workaround).

I encountered the same problem but I didn't update to .net 8.0. I use persistence with entity framework (MSSQL). The key parameters were left blank for no apparent reason. We resolved this by deleting the table and restarting the API (workaround).

**Comment by kirill-gerasimenko-da** [comment]
Having the same issue here. Will try to clear up the table as others suggested.

**Comment by maryammadzadeh** [comment]
This is pretty back, I had this happen while I was upgrading to dotnet 8, so I had to clear my storage to get this error to stop.  
Microsoft.IdentityModel.Protocols.OpenIdConnect released a new package yesterday (7.1.2), and the same 

error
System.NotSupportedException: 'IDX10621: 'Microsoft.IdentityModel.Tokens.SymmetricSignatureProvider' supports: 'Microsoft.IdentityModel.Tokens.SecurityKey' of types: 'Microsoft.IdentityModel.Tokens.AsymmetricSecurityKey' or 'Microsoft.IdentityModel.Tokens.SymmetricSecurityKey'. SecurityKey received was of type 'Microsoft.IdentityModel.Tokens.JsonWebKey'.'

came back. It required us to have to nuke the data again.

**Comment by sherlock1982** [comment]
Well If it helps here's an example. 

I create a key in .NET 7 and here's what I got in Parameters JSON in .NET 8:

`{\"AdditionalData\":{},\"Alg\":null,\"Crv\":null,\"D\":null,\"DP\":null,\"DQ\":null,\"E\":null,\"K\":\"CMUA71g93z9hiS8rt9NvOjBbZybfb--E2Z6AQXXKgaEzgH3LPscuSZbxfgkYctXxuiY9JGBsAOZF1huACm0aEw\",\"KeyId\":\"P99aRZA-6lJvOdxziITJ6A\",\"KeyOps\":[],\"Kid\":\"P99aRZA-6lJvOdxziITJ6A\",\"Kty\":\"oct\",\"N\":null,\"Oth\":null,\"P\":null,\"Q\":null,\"QI\":null,\"Use\":null,\"X\":null,\"X5c\":[],\"X5t\":null,\"X5tS256\":null,\"X5u\":null,\"Y\":null,\"KeySize\":512,\"HasPrivateKey\":false,\"CryptoProviderFactory\":{\"CryptoProviderCache\":{},\"CustomCryptoProvider\":null,\"CacheSignatureProviders\":true,\"SignatureProviderObjectPoolCacheSize\":64}}
`

Natively created key in .NET 8 

`{\"k\":\"gnq_e_lwxyCCg5BYsEKkG55pmO6_5ovKvSPr3aQ3fAVpVaSDkLeSklKDtJFPfpzESafCje0Qj1gsomig0PYBug\",\"key_ops\":[],\"kid\":\"yOxMeogeghirusdCfGdqBA\",\"kty\":\"oct\",\"oth\":[],\"x5c\":[]}`

Well the thing is that this is of course incompatible. 
Are there any conversion procedures we can apply?

**Comment by sherlock1982** [comment]
Ok I found a fix :-)

    public JsonWebKey GetSecurityKey()
    {
        return JsonSerializer.Deserialize<JsonWebKey>(Parameters, new JsonSerializerOptions() { 
            PropertyNameCaseInsensitive = true,
        });
    }
