### ISSUE TITLE
Warning and retention clarification

### ISSUE THREAD

**Issue by sherlock1982** [NetDevPack/Security.Jwt#51]
1. When I launch the app I see the following warning:
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[15]
      Unknown element with name 'NetDevPackSecurityJwt' found in keyring, skipping.

Is it anyhow an issue? I understand that NetDevPackSecurity stores my keys in the same folder as ASP.NET but looks like their XML files start with `<key>` and NetDevPackSecurity uses `<NetDevPackSecurityJwt>` root.
Is it intentional? 

2. I see in ASP.NET files . Does NetDevPackSecurity also encrypts keys?

3. I have multiple files from NetDevPackSecurity there (6 actually). Do I need to do something special to cleanup them? Well I changed key type couple of times - maybe that's why. Looks like expiration dates are not yet expired.

I went to that folder and made a key expired. Specifically changed `expirationDate`. But it still uses it and the file is still there. Are files anyhow deleted from there?

**Comment by brunobritodev** [comment]
> 1. When I launch the app I see the following warning:
>    warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[15]
>    Unknown element with name 'NetDevPackSecurityJwt' found in keyring, skipping.
> 
> Is it anyhow an issue? I understand that NetDevPackSecurity stores my keys in the same folder as ASP.NET but looks like their XML files start with `<key>` and NetDevPackSecurity uses `<NetDevPackSecurityJwt>` root. Is it intentional?

Yes, this is done intentionally

> 2. I see in ASP.NET files . Does NetDevPackSecurity also encrypts keys?

Yes, NetDevPackSecurity ensures that every stored key is securely encrypted using IDataProtector.

> 3. I have multiple files from NetDevPackSecurity there (6 actually). Do I need to do something special to cleanup them? Well I changed key type couple of times - maybe that's why. Looks like expiration dates are not yet expired.

No special action is required. Under the hood it use IXmlRepository, which is managed by ASP.NET.
