### ISSUE TITLE
How can I migrate an old ES256 key file to the database?

### ISSUE THREAD

**Issue by l0gaw** [NetDevPack/Security.Jwt#56]
I have a current key stored in the file format with the old alg ES256. Now the default is RSA. I'm trying to migrate from File store to the Database using EF but I wouldn't like my users to lose their current jwt.  Is there a way to migrate the old key file to the database? The new keys would be generated using the alg RSA.

**Comment by brunobritodev** [comment]
Yes, but definetely will not a simple task. You need to inject [FileSystemStore](https://github.com/NetDevPack/Security.Jwt/blob/master/src/NetDevPack.Security.Jwt.Store.FileSystem/FileSystemStore.cs) and [IJsonWebKeyStore](https://github.com/NetDevPack/Security.Jwt/blob/master/src/NetDevPack.Security.Jwt.Core/Interfaces/IJsonWebKeyStore.cs), then use `FileSystemStore.GetCurrent()` to get current Key, after that call IJsonWebKeyStore.Store().

Sure it helps
