### ISSUE TITLE
if the .key file has ExpiredAt and expired, it will always generate new .key file

### ISSUE THREAD

**Issue by liugt34** [NetDevPack/Security.Jwt#58]
in FileSystemStore.cs
this code always return the first file, so it will generate new file repeatly.

```
private string GetCurrentFile()
{
    var files = Directory.GetFiles(KeysPath.FullName, $"*current*.key");
    if (files.Any())
        return Path.Combine(KeysPath.FullName, files.First());

    return Path.Combine(KeysPath.FullName, $"{_options.Value.KeyPrefix}current.key");
}
```

**Comment by brunobritodev** [comment]
Thank you for your highlight at [FileSystemStore.cs](https://github.com/NetDevPack/Security.Jwt/blob/91e866ade1cf2883cc93e1b57c0b78d0fcaa1732/src/NetDevPack.Security.Jwt.Store.FileSystem/FileSystemStore.cs#L27).

The [JwtService](https://github.com/NetDevPack/Security.Jwt/blob/91e866ade1cf2883cc93e1b57c0b78d0fcaa1732/src/NetDevPack.Security.Jwt.Core/Jwt/JwtService.cs#L33) class is designed with a mechanism to check if the current security key is expired or needs to be updated for any reason (e.g., revocation). During process to generate new key it get the `*current*` key and copy it to `old-yyyy-MM-dd` file. After that a new Key will get place in `*current*` key.
